version: "3.8"
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=todo
    ports:
      - "3306:3306"
    restart: on-failure
  
  backend:
    build: ./backend
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_DB=todo
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: on-failure
  
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: on-failure